development:
  # adapter: async
  adapter: redis
  url: redis://127.0.0.1:6379/0
  channel_prefix: myblog_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: myblog_production