App.post = App.cable.subscriptions.create "PostChannel",

  connected: ->
    # Called when the subscription is ready for use on the server

  disconnected: ->
    # Called when the subscription has been terminated by the server

  received: (data) ->
    # Called when there's incoming data on the websocket for this channel
    if data['title'] == "書籍や漫画を読んだ"
      $('#posts').after('<tr><td class="balloon px-0"><div class="faceicon"><img src="' + data['bookcover'] + '" /></div><div class="chatting"><div class="says"><p class="font-weight-bold text-secondary d-inline-block" style="opacity: 0.87; word-break: break-all;">' + data['booktitle'] + '</p><small class="text-secondary"><br>' + data['bookauthor'] + '<br>' + data['bookpublisher'] + '<br></small><div class="obi font-weight-bold bg-success">読みました！</div><p class="font-weight-bold text-secondary d-inline-block" style="opacity: 0.87; word-break: break-all;">' + data['body'] + '</p><br><small style="float: right;" class="mt-2 text-secondary"><span class="oi oi-person" title="投稿者" aria-hidden="true"></span> <a href="' + data['cablebokensha'] + '">' + data['display_name'] + '</a> Lv.' + data['level'] + ' <span class="oi oi-clock my-1" title="' + data['cabledate1'] + '" aria-hidden="true"> <a href="' + data['mstdn_status'] + '" target="_blank"><span data-livestamp="' + data['cabledate2'] + '"></span></a></span></small></div></div></td></tr>')
    # else if data['image']?
    #   $('#posts').after('<tr><td><div class="card text-white bg-danger mb-3" style="max-width: 18rem;"><a data-turbolinks="false" href="posts/' + data['id'] + '"><div class="trim"><img class="card-img-top" src="' + data['image'] + '" /></div></a><a class="card-body" href="' + data['id'] + '"><h5 class="card-title text-white d-inline-block"><span class="oi oi-task" title="サブクエスト" aria-hidden="true"></span> 新着サブクエスト ⚔</h5><p class="card-text font-weight-bold text-white d-inline-block text-truncate my-1" style="max-width: 220px; opacity: 0.87;">' + data['body'] + '</p></a></div></div></td></tr>')
    #   $('#socialparam').replaceWith('<tr id="socialparam" class="text-center"><td class="pt-0">' + data['bokenshanum'] + '名</td><td class="pt-0">' + data['clearnum'] + '件</td><td class="pt-0">平均Lv.' + data['levelavrg'] + '</td></tr>')
    #   $('#socialparam2').replaceWith('<tr id="socialparam2" class="text-center"><td class="pt-0">' + data['bokenshanum'] + '名</td><td class="pt-0">' + data['clearnum'] + '件</td><td class="pt-0">平均Lv.' + data['levelavrg'] + '</td></tr>')
    else if data['title'] == "新規サブクエスト"
      $('#posts').after('<tr><td class="px-0"><div class="card text-white text-center bg-danger my-1 tilt" style="max-width: 18rem;"><a class="card-body bg-danger d-inline-block stretched-link" href="/posts/' + data['id'] + '"><h5 class="card-title text-white d-inline-block wf-nicomoji"><span class="oi oi-task" title="サブクエスト" aria-hidden="true"></span> サブクエスト ⚔</h5><br><p class="card-text font-weight-bold text-white d-inline-block text-truncate my-0" style="max-width: 220px; opacity: 0.87;">' + data['body'] + '</p></a></div></td></tr>')
    else if data['title'] == "公式のつぶやき"
      $('#posts').after('<tr><td class="px-0"><div class="box26"><span class="box-title"><span class="oi oi-wifi text-primary" title="読んでね" aria-hidden="true"></span> 公式のつぶやき</span><p>' + data['body'] + '<br><span style="font-size: 0.8em; float: right;" class="mt-2 text-secondary"><span class="oi oi-clock my-1" title="' + data['cabledate1'] + '" aria-hidden="true"> <a href="' + data['mstdn_status'] + '" target="_blank"><span data-livestamp="' + data['cabledate2'] + '"></span></a></span></span></p></div></td></tr>')
    else if data['title'] == "ニュース"
      $('#posts').after('<tr><td class="px-0"><div class="card text-white bg-white mt-2 mb-1" style="max-width: 18rem;"><a href="' + data['newsurl'] + '" target="_blank" rel="noopener noreferrer"><div class="trim news"><img class="card-img-top" onerror="this.src=&#39;/assets/ogpimage.png&#39;" src="' + data['newsimage'] + '" /><small class="news-badge">ニュース</small></div></a><a class="bg-secondary px-2 pt-1 pb-1" href="' + data['newsurl'] + '" target="_blank" rel="noopener noreferrer"><small class="font-weight-bold text-white mt-1" style="word-break: break-all;">' + data['newstitle'] + '</small></a><p class="card-text font-weight-bold text-secondary mt-2 mb-1 px-2" style="word-break: break-all; text-align: justify;">' + data['body'] + '</p><p class="px-2 mb-2"><small style="float: right;" class="text-secondary"><span class="oi oi-person" title="投稿者" aria-hidden="true"></span> <a href="' + data['cablebokensha'] + '">' + data['display_name'] + '</a> Lv.' + data['level'] + '<span class="oi oi-clock my-1" title="' + data['cabledate1'] + '" aria-hidden="true"> <a href="' + data['mstdn_status'] + '" target="_blank"><span data-livestamp="' + data['cabledate2'] + '"></span></a></span></small></p></div></td></tr>')
    else if data['title'] == "駅でチェックイン"
      $('#posts').after('<tr><td class="balloon77 px-0"><div class="faceicon"><img onerror="this.src=&#39;/assets/missing.png&#39;" src="' + data['avatar'] + '" /></div><div class="chatting"><div class="says"><small class="oi oi-compass mb-2" title="駅" aria-hidden="true"> <a target="_blank" href="https://maps.google.co.jp/maps?q=' + data['stationname'] + '">' + data['stationname'] + '</a></small><br><p class="font-weight-bold text-secondary d-inline-block" style="opacity: 0.87; word-break: break-all;">' + data['body'] + '</p><small style="float: right;" class="mt-2 text-secondary"><span class="oi oi-person" title="投稿者" aria-hidden="true"></span> <a href="https://' + data['cabledomain'] + '/@' + data['cablebokensha'] + '">' + data['display_name'] + '</a> Lv.' + data['level'] + ' <span class="oi oi-clock my-1" title="' + data['cabledate1'] + '" aria-hidden="true"> <a href="' + data['mstdn_status'] + '" target="_blank"><span data-livestamp="' + data['cabledate2'] + '"></span></a></span></small></div></div></td></tr>')
    else if data['title'] == "冒険中のつぶやき"
      $('#posts').after('<tr><td class="balloon77 px-0"><div class="faceicon"><img onerror="this.src=&#39;/assets/missing.png&#39;" src="' + data['avatar'] + '" /></div><div class="chatting"><div class="says"><p class="font-weight-bold text-secondary d-inline-block" style="opacity: 0.87; word-break: break-all;">' + data['body'] + '</p><small style="float: right;" class="mt-2 text-secondary"><span class="oi oi-person" title="投稿者" aria-hidden="true"></span> <a href="' + data['cablebokensha'] + '">' + data['display_name'] + '</a> Lv.' + data['level'] + ' <span class="oi oi-clock my-1" title="' + data['cabledate1'] + '" aria-hidden="true"> <a href="' + data['mstdn_status'] + '" target="_blank"><span data-livestamp="' + data['cabledate2'] + '"></span></a></span></small></div></div></td></tr>')
    else if data['title'] == "復活の呪文でHP回復"
      $('#posts').after('<tr><td class="balloon77 px-0"><div class="faceicon"><img onerror="this.src=&#39;/assets/missing.png&#39;" src="' + data['avatar'] + '" /></div><div class="chatting"><div class="says"><p class="font-weight-bold text-secondary d-inline-block" style="opacity: 0.87; word-break: break-all;">' + data['body'] + '</p><small style="float: right;" class="mt-2 text-secondary"><span class="oi oi-person" title="投稿者" aria-hidden="true"></span> <a href="' + data['cablebokensha'] + '">' + data['display_name'] + '</a> Lv.' + data['level'] + ' <span class="oi oi-clock my-1" title="' + data['cabledate1'] + '" aria-hidden="true"> <a href="' + data['mstdn_status'] + '" target="_blank"><span data-livestamp="' + data['cabledate2'] + '"></span></a></span></small></div></div></td></tr>')

  speak: (body, id, title, uid, image, avatar, level, cableuser, cabledomain, cablebokensha, display_name, cabledate1, cabledate2, booktitle, bookpublisher, bookauthor, bookcover, newsurl, newsimage, newstitle, stationname, mstdn_status) ->
    @perform 'speak', {body: post.body, id: post.id, title: post.title, uid: post.post_uid, image: post.image, avatar: user.avatar, level: user.level, cableuser: cableuser, cablebokensha: cablebokensha, display_name: display_name, cabledate1: cabledate1, cabledate2: cabledate2, booktitle: post.booktitle, bookpublisher: post.bookpublisher, bookauthor: post.bookauthor, bookcover: post.bookcover, newsurl:post.newsurl, newsimage: post.newsimage, newstitle: newstitle, stationname: post.stationname, mstdn_status: post.mstdn_status}

    $(document).on 'keypress', '[data-behavior~=speak_posts]', (event) ->
    if event.keyCode is 13
        App.post.speak event.target.value
        event.target.value = ''
        event.preventDefault()